using System.Collections.Generic;
using System.Windows.Controls;

namespace TTMSViewWPF.View.Pages
{

    class MoviesSales
    {
        public string MovieName { get; set; }
        public int Sales { get; set; }
        public string States { get; set; }
    }

    class AuditoriumInCome
    {
        public string AuditoriumName { get; set; }
        public int Sales { get; set; }
        public string States { get; set; }
    }

    class SalespersonSales
    {
        public string SalespersonName { get; set; }
        public int Sales { get; set; }
        public string States { get; set; }
    }

    /// <summary>
    /// SalesInfoManagementPage.xaml 的交互逻辑
    /// </summary>
    public partial class SalesInfoManagementPage : Page
    {
        public SalesInfoManagementPage(MainWindow mainWindow)
        {
            InitializeComponent();
            _Init();
        }

        private void _Init()
        {
            _InitMoviesSalesDataGrid();
            _AuditoriumInComeDataGrid();
            _SalespersonSalesDataGrid();
        }

        private void _SalespersonSalesDataGrid()
        {
            var lm = new List<SalespersonSales>()
            {
                new SalespersonSales()
                {
                    SalespersonName = "杨帆" ,
                    Sales = 275 ,
                    States = "平稳"
                },
                new SalespersonSales()
                {
                    SalespersonName = "李一斐" ,
                    Sales = 264 ,
                    States = "下降"
                },
                new SalespersonSales()
                {
                    SalespersonName = "余帆" ,
                    Sales = 199 ,
                    States = "上升"
                },
                new SalespersonSales()
                {
                    SalespersonName = "扈衍" ,
                    Sales = 188 ,
                    States = "平稳"
                },
                new SalespersonSales()
                {
                    SalespersonName = "南继东" ,
                    Sales = 124 ,
                    States = "下降"
                }

            };
            SalespersonSalesDataGrid.ItemsSource = lm;

            SalespersonSalesDataGrid.AutoGeneratedColumns += (sender, args) =>
            {
                SalespersonSalesDataGrid.Columns[0].Header = "售票员名称";
                SalespersonSalesDataGrid.Columns[1].Header = "销售量";
                SalespersonSalesDataGrid.Columns[2].Header = "增长趋势";
            };
        }

        private void _AuditoriumInComeDataGrid()
        {
            var lm = new List<AuditoriumInCome>()
            {
                new AuditoriumInCome()
                {
                    AuditoriumName = "西邮一号放映厅" ,
                    Sales = 24556 ,
                    States = "上升"
                },
                new AuditoriumInCome()
                {
                    AuditoriumName = "西邮二号放映厅" ,
                    Sales = 24556 ,
                    States = "下降"
                },
                new AuditoriumInCome()
                {
                    AuditoriumName = "师范放映厅" ,
                    Sales = 23404 ,
                    States = "下降"
                },
                new AuditoriumInCome()
                {
                    AuditoriumName = "政法放映厅" ,
                    Sales = 19956,
                    States = "上升"
                },

            };
            AuditoriumInComeDataGrid.ItemsSource = lm;

            AuditoriumInComeDataGrid.AutoGeneratedColumns += (sender, args) =>
            {
                AuditoriumInComeDataGrid.Columns[0].Header = "影厅名称";
                AuditoriumInComeDataGrid.Columns[1].Header = "收入";
                AuditoriumInComeDataGrid.Columns[2].Header = "增长趋势";
            };


        }

        private void _InitMoviesSalesDataGrid()
        {
            var lm = new List<MoviesSales>()
            {
                new MoviesSales()
                {
                    MovieName = "记忆大师" , 
                    Sales = 245 , 
                    States = "平稳"
                },
                new MoviesSales()
                {
                    MovieName = "急速追杀2" ,
                    Sales = 234 ,
                    States = "下降"
                },
                new MoviesSales()
                {
                    MovieName = "生化危机终章" ,
                    Sales = 199 ,
                    States = "上升"
                },
                new MoviesSales()
                {
                    MovieName = "美女与野兽" ,
                    Sales = 178 ,
                    States = "平稳"
                },
                new MoviesSales()
                {
                    MovieName = "大闹天竺" ,
                    Sales = 134 ,
                    States = "下降"
                },
                new MoviesSales()
                {
                    MovieName = "一只狗的使命" ,
                    Sales = 99 ,
                    States = "上升"
                }
            };
            MovieSalesDataGrid.ItemsSource = lm;

            MovieSalesDataGrid.AutoGeneratedColumns += (sender, args) =>
            {
                MovieSalesDataGrid.Columns[0].Header = "剧目名称";
                MovieSalesDataGrid.Columns[1].Header = "销量";
                MovieSalesDataGrid.Columns[2].Header = "增长趋势";
            };


        }
    }
}
